# Generated by Django 3.0.8 on 2020-07-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('duration', models.PositiveSmallIntegerField(default=30)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
